root: true
extends:
  - airbnb
  - prettier
env:
  node: true
  es6: true
rules:
  "no-console": off
  "prettier/prettier":
    - error
    - singleQuote: true
      semi: true
  "flowtype-errors/show-errors": error
  "flowtype-errors/show-warnings": warn
plugins:
  - import
  - prettier
  - flowtype
  - "flowtype-errors"
settings:
  "import/resolve":
    moduleDirectory:
      - node_modules
      - src
parser: "babel-eslint"
parserOptions:
  sourceType: module
